/* **** The fundamental basic-skeleton is generated by QGIS **** */
/* **** Leaflet **** */

//  .. OpenStreetMap for background
var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors', minZoom: 10, maxZoom: 15});

// Overlay layers (TMS)
var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 1, attribution: '&copy; <a href="https://www.cottbus.de/verwaltung/gb_iv/stadtentwicklung/">Stadtentwicklung Cottbus</a>, 12/2021, <a href="https://stadtentwicklung.github.io/masterplan-english/"><b>ENGLISH</b></a>, <a href="https://stadtentwicklung.github.io/masterplan-polski/"><b>POLSKI</b></a>, <a href="https://stadtentwicklung.github.io/masterplan-dolnoserbski/"><b>DOLNOSERBSKI</b></a>', minZoom: 10, maxZoom: 15});

// Map
var map = L.map('map', {
    center: [51.78179619043856, 14.430890490667228],
    //zoom: 15,
    minZoom: 10,
    maxZoom: 15,
    layers: [osm, lyr],
	loadingControl: true
});

// Title
var title = L.control();
title.onAdd = function(map) {
    this._div = L.DomUtil.create('div', 'ctl title');
    this.update();
    return this._div;
};

title.update = function(props) {
    this._div.innerHTML = "Masterplan Cottbuser Ostsee 3.0";
};
title.addTo(map);

// Fit to overlay bounds (SW and NE points with (lat, lon))
map.fitBounds([[51.72837123461897, 14.552784241190125], [51.83522114625816, 14.30899674014433]]);
		
// Geolocating		
function onLocationFound(e) {
    var location = e.latlng
    L.marker(location).addTo(map).bindPopup("Du bist ungef&auml;hr hier.").openPopup();
};

function onLocationError(e) {
	alert(e.message);
};

function getLocationLeaflet() {
	map.on('locationfound', onLocationFound);
	map.on('locationerror', onLocationError);
	map.locate({setView: true, maxZoom: 15});
};
		
// Custom project-marker
var redIcon = new L.Icon({
	iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
	shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
	iconSize: [25, 41],
	iconAnchor: [12, 41],
	popupAnchor: [1, -34],
	shadowSize: [41, 41]
});

//1
L.marker([51.77727, 14.39582], {icon: redIcon}).addTo(map).bindPopup("<p><strong>1. Hafenquartier Cottbus | P&sacute;istawowy kwart&ecaron;r Ch&oacute;&sacute;ebuz</strong></p><img src='./img/1_hafen.jpg'/><p>Mit dem Hafenquartier wird Cottbus/Ch&oacute;sebuz eine &bdquo;Stadt am Wasser&ldquo;. Am Endpunkt der Seeachse entsteht zwischen dem Ufer des Cottbuser Ostsees und der B168 ein neues innovatives und vielf&auml;ltiges Quartier mit Promenade, Stadthafen und etwa 200 Bootsliegepl&auml;tzen. Neben einem breit gef&auml;cherten Wassersportbereich, einem Sport- und Gesundheitszentrum, Wohnungen, Gesch&auml;ften, Restaurants sowie einem Hotel- und Veranstaltungskomplex entsteht das &bdquo;Forum Lausitz/Carboneum&ldquo; &ndash; ein Infozentrum zur wechselvollen Beziehung zwischen der Kulturgeschichte, dem Naturraum und der Kohlef&ouml;rderung in der Region. Das Hafenquartier soll als erstes Quartier in Cottbus/Ch&oacute;sebuz dem Anspruch einer Kohlendioxid-neutralen Stadtentwicklung gerecht werden. Beginnend bei der Planung, Materialwahl und Konstruktion &uuml;ber eine innovative Mobilit&auml;tskonzeption bis hin zur Kohlendioxid-neutralen Energieversorgung soll das Hafenquartier bundesweit Ma&szlig;st&auml;be f&uuml;r eine nachhaltige und klimagerechte urbane Entwicklung setzen.</p>");
//2
L.marker([51.77004, 14.37917], {icon: redIcon}).addTo(map).bindPopup("<p><strong>2. Seevorstadt | Jazorowe p&sacute;edm&ecaron;sto</strong></p><img src='./img/2_vorstadt.jpg'/><p>Die st&auml;dtebauliche Verbindung zwischen Innenstadt und Cottbuser Ostsee ist eines der wichtigsten Projekte in den n&auml;chsten Jahrzehnten und Initial einer Kohlendioxid-neutralen und klimaresilienten Entwicklung von Cottbus/Ch&oacute;sebuz. Kern dieser Verbindung ist die ehemalige Bahntrasse Cottbus -Guben, die im Jahr 2000 durch den Tagebau obsolet wurde. Hier soll ein urbaner gr&uuml;ner Freiraum f&uuml;r Fu&szlig;g&auml;nger, Radfahrer und den &Ouml;PNV entstehen. Die stadtr&auml;umliche Ausrichtung hin zum Wasser wird dabei durch die Entwicklung der Seevorstadt entlang dieser Verbindungsachse flankiert. Hier entsteht ein Zukunftsraum in Form eines modernen, urbanen und nachhaltigen Stadtquartiers und gro&szlig;z&uuml;gigen Gr&uuml;nr&auml;umen. Die Planungen sehen neue Wohnbereiche, attraktive Gewerbefl&auml;chen, einen innovativen Energiecampus als Denkfabrik sowie ein Bildungs- und Beh&ouml;rdenzentrum mit zahlreichen Arbeitspl&auml;tzen vor. Neue Funktionen und Gestaltungsqualit&auml;ten im Sinne eines grundlegenden Stadtumbauprozesses sowie innovativer &ouml;ffentlicher Nahverkehr definieren die Anspr&uuml;che an die zuk&uuml;nftige Stadtentwicklung im Cottbuser Osten.</p>");
//3
L.marker([51.78746, 14.38042], {icon: redIcon}).addTo(map).bindPopup("<p><strong>3. Merzdorf | &Zcaron;ylowk</strong></p><p>Nordwestlich, in unmittelbarer Nachbarschaft zum Hafenquartier entstehen Wohnbebauungen als Erg&auml;nzung zum Siedlungsgebiet von Merzdorf mit dem Vorzug der N&auml;he zur Stadt und zum Wasser. Hier sollen Wohnungen in moderner Architektursprache und dem Anspruch an eine Kohlendioxid-neutrale Stadtentwicklung entstehen. Flankiert wird das Quartier durch den Merzdorfer Strand, der vor allem f&uuml;r Cottbuser Badeg&auml;ste mit dem Fahrrad und zu Fu&szlig; gut erreichbar ist.</p>");
//4
L.marker([51.7975, 14.38316], {icon: redIcon}).addTo(map).bindPopup("<p><strong>4. Lakoma &ndash; Willmersdorf | &Lstrok;akoma &ndash; Rogozno</strong></p><p>Die ehemalige Dorflage Lakoma bildet den zentralen Knotenpunkt am See f&uuml;r Radfahrer zwischen See-Rundweg und (&uuml;ber-)regionalen Radwanderwegen bzw. umgekehrt. Vor dem Westufer des Cottbuser Ostsees soll eine schwimmende Insel mit Gastst&auml;tte und Ferienwohnungen entstehen. Der naturbelassene Uferabschnitt mit Uferweg l&auml;dt zu Seespazierg&auml;ngen unmittelbar am Wasser ein. N&ouml;rdlich von Lakoma befindet sich der Willmersdorfer Strand, der ideal f&uuml;r Badeg&auml;ste aus dem lokalen Umfeld aber auch f&uuml;r Radtouristen entlang des Rundweges geeignet ist.</p>");
//5
L.marker([51.80482, 14.42282], {icon: redIcon}).addTo(map).bindPopup("<p><strong>5. Hafen Teichland | P&sacute;istaw Gatojce</strong></p><img src='./img/5_teichland.jpg'/><p>Am s&uuml;dlichen Rand des Ortsteils Neuendorf der Gemeinde Teichland entsteht ein &bdquo;Seehafen&ldquo;. Die Planung sieht die Errichtung eines Sportboothafens mit einer Wasserfl&auml;che von ca. 16.000 Quadratmeter f&uuml;r 100 Bootsliegepl&auml;tze vor. Um das k&uuml;nftige Hafenbecken wird ein Hafenquartier mit einer Seepromenade, die einen Ausblick &uuml;ber den Hafen und auf den Ostsee bietet, entstehen. Die Pormenade bindet im Osten an die &bdquo;Seeachse&ldquo; an und f&uuml;hrt weiter zur Anlegestelle f&uuml;r die Fahrgastschifffahrt und zum &bdquo;Erlebnispark&ldquo;. An der Promenade angelagert sind Fl&auml;chen f&uuml;r maritimes Gewerbe, Gastronomie und Beherbergungsst&auml;tten. Weiterhin sind im Hafenquartier Fl&auml;chen f&uuml;r Hafenbetrieb, Werkstatt, Bootslagerhalle sowie Ferienwohnungen und&nbsp; -h&auml;user geplant. Baufl&auml;chen f&uuml;r Wohnh&auml;user tragen zur ganzj&auml;hrigen Belebung des Quartiers bei.</p>");
//6
L.marker([51.80745, 14.44994], {icon: redIcon}).addTo(map).bindPopup("<p><strong>6. B&auml;renbr&uuml;cker H&ouml;he | Barbucka wu&scaron;yna<br /></strong></p><p>Die B&auml;renbr&uuml;cker H&ouml;he ist eine k&uuml;nstliche Erhebung, die ca. 30 m &uuml;ber dem nat&uuml;rlichen Umland liegt. Gemeinsam mit dem Erlebnispark &bdquo;Teichland&ldquo; und dem Aussichtsturm bildet sie das Zentrum der touristischen Angebote am n&ouml;rdlichen Seeufer. Im Erlebnispark befinden sich neben einer Sommerrodelbahn, ein Zipline Parcours, Kletterfelsen, ein Irrgarten, der &bdquo;&sbquo;Slawische G&ouml;tterhain&ldquo; und der &bdquo;Pfad der kleinen G&ouml;tter&ldquo;. Der Aussichtsturm erm&ouml;glicht einen weiten Blick auf den zuk&uuml;nftigen See.</p>");
//7
L.marker([51.79691, 14.44921], {icon: redIcon}).addTo(map).bindPopup("<p><strong>7. B&auml;renbr&uuml;cker Bucht | Barbucka wu&scaron;yna<br /></strong></p><p>Die B&auml;renbr&uuml;cker Bucht eignet sich ideal f&uuml;r l&auml;rmintensivere Veranstaltungen von Musik, &uuml;ber Schauspiel bis hin zu Gro&szlig;- und Privatveranstaltungen. Zudem ist sie der Surfpoint am See. Die Wasserfl&auml;che und der Strand in der Bucht bieten mit ihrer S&uuml;dausrichtung beste Verh&auml;ltnisse f&uuml;r Kite Surfer. Saisonale Gastronomie, Surfschul- und Verleihangebote sowie eine Zeltwiese, ein Wohnmobilstellplatz und ein gro&szlig;es Sportfeld sollen unter dem Anspruch des Kohlendioxid-neutralen Bauens und des schonenden Umgangs mit Ressourcen als Planungspr&auml;misse, Raum f&uuml;r nachhaltigen aktiven Wassersporttourismus bieten.</p>");
//8
L.marker([51.78252, 14.47835], {icon: redIcon}).addTo(map).bindPopup("<p><strong>8. Energiezentrum | Energijowy centrum<br /></strong></p><p>Auf den ehemaligen Tagesanlagen des Braunkohletagebaus entsteht ein Wirtschaftsstandort f&uuml;r Industrie und produzierendes Gewerbe mit Fokus auf Erneuerbare Energien und Kreislaufwirtschaft. Das verkehrlich gut erschlossene Gewerbegebiet der heutigen Tagesanlagen soll zu einem Technologie- und Gr&uuml;nderzentrum f&uuml;r Zukunftsenergien (Schwerpunkt nachwachsende Rohstoffe, alternative Energiegewinnung) auf einer Gesamtfl&auml;che von ca. 55 ha ausgebaut werden.</p>");
//9
L.marker([51.78239, 14.4593], {icon: redIcon}).addTo(map).bindPopup("<p><strong>9. Energielandschaft | Energijowa krajina<br /></strong></p><p>&Ouml;stlich des Sees, zwischen Rundweg und Energiezentrum, wird eine gr&uuml;ne Energielandschaft vorgeschlagen. Schwerpunkt soll zuk&uuml;nftig die Erzeugung erneuerbarer Energien im Einklang mit der &uuml;berwiegend forstwirtschaftlich und naturnah gepr&auml;gten Nachnutzung der Bergbaufolgelandschaft sein. Anlagen zur Umwandlung von Wind- und Sonnenergie in Strom verk&ouml;rpern hier den Wandel der Energieversorgung. Besucher k&ouml;nnen sich an Infotafeln entlang des Rundweges &uuml;ber die Historie der Energiegewinnung informieren.</p>");
//10
L.marker([51.75012, 14.48234], {icon: redIcon}).addTo(map).bindPopup("<p><strong>10. Klinger See | Klincanski jazor</strong></p><p>Dem Klinger See wird mit der Schaffung und dem Erhalt von wertvollen Natur- und Landschaftsarealen sowie der Entwicklung eines naturnahen Tourismus besondere Bedeutung einger&auml;umt. Durch seine Ausformung ist er pr&auml;destiniert f&uuml;r eine professionelle Regattastrecke &uuml;ber 2.500 bis 3.000 m. Ein &bdquo;Rudersportzentrum&ldquo; fast das Wassersportangebot k&uuml;nftig sehr zentral zusammen und k&ouml;nnte von vielen Sportvereinen genutzt werden. Mit der Freigabe des Sees ist aufgrund des prognostizierten Abschlusses der Flutung deutlich nach der Fertigstellung des Cottbuser Ostsees zu rechnen.</p>");
//11
L.marker([51.74994, 14.44685], {icon: redIcon}).addTo(map).bindPopup("<p><strong>11. Naturstrand S&uuml;dspitze | P&sacute;irodny p&oacute;dpo&lstrok;dnjowy p&sacute;ibrjog</strong></p><p>Aufgrund seiner Erhebung ist dieses Areal die visuelle Schnittstelle zwischen dem Klinger See und dem Cottbuser Ostsee. Hier soll auf einer L&auml;nge von ca. 250 m der Naturstrand des Sees f&uuml;r Freunde der Freik&ouml;rperkultur und Badeg&auml;ste mit hohem Naturbed&uuml;rfnis angelegt werden. Eine intensive Freizeit- und Tourismusnutzung ist daher nicht vorgesehen. Der Strand ist zu Fu&szlig; und mit dem Fahrrad entlang des Rundweges erreichbar.</p>");
//12
L.marker([51.75482, 14.41677], {icon: redIcon}).addTo(map).bindPopup("<p><strong>12. Entwicklungsraum Schlichow-S&uuml;d | Wuwija&nacute;ski rum &Scaron;lichow&ndash;p&oacute;dpo&lstrok;dnjo</strong></p><p>S&uuml;dlich der Ortslage Schlichow bildet eine k&uuml;nstlich geschaffene, bewegte Landschaft den Auftakt der Binnend&uuml;nenlandschaft entlang des S&uuml;dwestufers. Hier sind gro&szlig;fl&auml;chige Freizeit- und Sportnutzungen denkbar, welche mit dem l&auml;ndlichen Charakter des Umfeldes korrespondieren und gleichzeitig vor allem ruhebed&uuml;rftige sowie naturaffine Ausfl&uuml;gler und Anwohner begeistern.</p>");
//13
L.marker([51.76131, 14.41381], {icon: redIcon}).addTo(map).bindPopup("<p><strong>13. Schlichow | &Scaron;lichow<br /></strong></p><p>Schlichow liegt direkt am zuk&uuml;nftigen Cottbuser Ostsee. Hier entstehen zus&auml;tzliche Wohnbaufl&auml;chen durch Arrondierung und Nachverdichtung. Mit der Gestaltung des Platzes am Anger als Scharnier zwischen Siedlung und Schiffsanleger am See entsteht eine neue Ortsmitte. Entlang des Platzes sind ein Mehrzweckgeb&auml;ude, ein Rast- und Servicepunkt f&uuml;r Radfahrer, eine E-Bike Ladestation sowie eine Radler Herberge geplant. Der durch die Einstellung des Tagebaus in seiner Funktion obsolete L&auml;rmschutzdamm soll auf Grundlage geeigneter Konzepte umgestaltet werden.</p>");
//14
L.marker([51.75772, 14.42844], {icon: redIcon}).addTo(map).bindPopup("<p><strong>14. Schlichow S&uuml;d | &Scaron;lichow P&oacute;dpo&lstrok;dnjowy<br /></strong></p><p>S&uuml;d&ouml;stlich von Schlichow soll aufgrund der Standortqualit&auml;ten ein kleines aber feines Urlauberzentrum f&uuml;r Sport und Wellness entstehen. Auch ein hoteleigener Strand und ein kleiner Steg sind denkbar. Der Strand ist f&uuml;r Fu&szlig;g&auml;nger und Radfahrer erreichbar. Sportboote und Slipanlagen wird es hier jedoch nicht geben, da diese ausschlie&szlig;lich in den beiden H&auml;fen am See vorgesehen sind.</p>");
//15
L.marker([51.76935, 14.40325], {icon: redIcon}).addTo(map).bindPopup("<p><strong>15. Cottbuser Strand | Ch&oacute;&sacute;ebuski p&sacute;ibrjog<br /></strong></p><p>Zwischen dem Stadthafen und Schlichow entsteht mit ca. 18 ha der Hauptstrand des Sees mit regionaler Ausstrahlung. Neben dem Badestrand und Sportm&ouml;glichkeiten bieten Sitzgelegenheiten, Versorgungseinrichtungen, Umkleiden, Sanit&auml;ranlagen sowie der Verleih von Liegen, Sonnenschirmen und Booten eine hohe Aufenthaltsqualit&auml;t. Der Strand ist &uuml;ber den Rundweg zu Fu&szlig;, mit Rad, mit Skates sowie &uuml;ber die B168 mit &Ouml;PNV und PKW gut zu erreichen. F&uuml;r die geplanten Nutzungen besteht ebenso wie f&uuml;r das benachbarte Hafenquartier der Anspruch an eine Kohlendioxid-neutrale Bauweise und einen ressourcenschonenden Betrieb.</p>");
//16
L.marker([51.74297, 14.36965], {icon: redIcon}).addTo(map).bindPopup("<p><strong>16. Schlosspark Branitz | Grodowy park Roge&nacute;c<br /></strong></p><p>Der Landschaftsraum um die Schlichower H&ouml;he soll landschaftsgestalterisch eine Verbindung mit der Branitzer Park- und Kulturlandschaft eingehen. Den Kern dieser Verbindung bildet die historische Kastanienallee, einst herrschaftliche Anfahrt zum Schloss und Park Branitz, als Fu&szlig;- und Fahrradweg. Das Thema Landschaftsgestaltung soll als Attraktionsmerkmal f&uuml;r den Cottbuser Ostsee genutzt werden. Der Branitzer Park ist die historische Kulturlandschaft, der Cottbuser Ostsee ihre moderne Interpretation.</p>");
//17
L.marker([51.76085, 14.462], {icon: redIcon}).addTo(map).bindPopup("<p><strong>17. Rundweg | Woko&lstrok;ny pu&sacute;<br /></strong></p><img src='./img/17_rundweg.jpg'/><p>Um den Cottbuser Ostsee herum entsteht ein 27 km langer Rundweg, der Wanderern, Radfahrern, Skatern und Joggern vorbehalten ist. Der &bdquo;Ostsee-Rundweg&ldquo; wird in das Brandenburger Radverkehrsnetz sowie die bereits vorhandenen regionalen Radwanderwege eingebunden. Der Weg verbindet die einzelnen Standorte, Projekte, Str&auml;nde und Hotels am Cottbuser Ostsee. Die Bedeutung des Rundweges soll durch eine hochattraktive landschaftsplanerische Ausformung, sowohl in der M&ouml;blierung (z.B. Sitzb&auml;nke, Infotafeln bei Raststationen etc.) als auch in der Oberfl&auml;chengestaltung, erlebbar werden.</p>");
//18
L.marker([51.7752, 14.44389], {icon: redIcon}).addTo(map).bindPopup("<p><strong>18. Lieskower Bucht | Li&scaron;kojski zalew<br /></strong></p><p>Das buchtenreiche Ostufer des Cottbuser Ostsees ist mit seinen vorgelagerten Inseln bzw. Halbinseln der naturbelassenen, gesch&uuml;tzten Entwicklung von Flora und Fauna vorbehalten. Die Entstehung einer Vogelinsel mit Beobachtungssteg soll an dieser Stelle bef&ouml;rdert werden.</p>");
//19
L.marker([51.74677, 14.45994], {icon: redIcon}).addTo(map).bindPopup("<p><strong>19. Seen-Radweg | Jazorowy k&oacute;lasa&racute;ski pu&sacute;<br /></strong></p><p>Eine Verlegung des F&uuml;rst-P&uuml;ckler-Radweges soll den Cottbuser Ostsee mit dem Klinger See verbinden und auf diese Weise die neu entstehende Seenlandschaft f&uuml;r den aktiven, naturnahen und Kohlendioxid-neutralen Rad- und Wandertourismus erlebbar machen. Hierf&uuml;r sind planfreie, unabh&auml;ngige Querungen der B97 und der Trasse der ehemaligen Grubenbahn angedacht.</p>");
//20
L.marker([51.78125, 14.42406], {icon: redIcon}).addTo(map).bindPopup("<p><strong>20. Seezeichen | Jazorowy znamje<br /></strong></p><p>Eine schwimmende Landmarke soll sowohl Blickfang und Imagetr&auml;ger als auch sichtbares Zeichen f&uuml;r den Strukturwandel werden. Der Standort markiert gleichzeitig die Mitte des Cottbuser Ostsees. Zur Ideenfindung wurde ein studentischer Wettbewerb an der BTU Cottbus-Senftenberg durchgef&uuml;hrt. Die besten Entwurfsideen werden durch die Stadtverwaltung Cottbus/Ch&oacute;sebuz und das Ostseemanagement in die weiteren Planungen zum Cottbuser Ostsee aufgenommen und die Realisierung gepr&uuml;ft.</p>");
//21
L.marker([51.76595, 14.40668], {icon: redIcon}).addTo(map).bindPopup("<p><strong>21. Sport-Dreieck Cottbuser Ostsee | Sportowy t&sacute;iro&zcaron;k Ch&oacute;&sacute;ebuski p&oacute;dzajt&scaron;ny jazor</strong></p><p>Im Rahmen der Realisierung des Strukturentwicklungsprojektes &bdquo;BMX Event- und Trainingszentrum im Sport- und Freizeitpark Cottbuser Ostsee&ldquo; sollen im s&uuml;dlichen Bereich des Cottbuser Ostsees auf H&ouml;he des Ortsteils Dissenchen neue Sport- und Freizeitnutzungen etabliert werden und den neu geschaffenen landschaftlich gepr&auml;gten Stadtraum am Wasser erlebbar machen. Ein Outdoor Park mit landseitigen Sportangeboten sowie kleineren baulichen Anlagen (WC, Verwaltung, Caf&eacute;) als untergeordnete Nutzung ist denkbar. F&uuml;r den Spitzen-, Freizeit-, Breiten- und Vereinssport st&uuml;nden mit dem &bdquo;Sport-Dreieck&ldquo; aus Stadthafen, BMX-Zentrum/Sport- und Freizeitpark sowie dem Outdoor Sportpark vielf&auml;ltige Angebote zur Verf&uuml;gung.</p>");
//22
L.marker([51.75496, 14.39642], {icon: redIcon}).addTo(map).bindPopup("<p><strong>22. BUGA 2033 - Vision | BUGA 2033 - wizija</strong></p><img src='./img/22_buga.jpg'/><p>In Cottbus/Ch&oacute;sebuz fand viereinhalb Jahre nach der deutschen Wiedervereinigung die erste Bundesgartenschau in den Neuen Bundesl&auml;ndern statt. Fast vier Jahrzehnte sp&auml;ter will Cottbus/Ch&oacute;sebuz wieder Gastgeber sein und den Besuchern aus Deutschland und Europa die nachhaltige Entwicklung des Zentrums der ehemaligen Tagebauregion pr&auml;sentieren. Ein BUGA-Konzept, welches die wechselvolle Geschichte von Stadt und Region erz&auml;hlt, gab es noch nie: Zwischen Innenstadt, dem Branitzer Park und dem Cottbuser Ostsee sollen vielf&auml;ltige Erlebnisr&auml;ume und Wanderpfade die Kulturgeschichte im Beziehungsgeflecht zwischen Natur, Technik, Wirtschaft, Gesellschaft, Kohleabbau, Energiegewinnung, Landschaftszerst&ouml;rung und Verlust nat&uuml;rlicher Lebensgrundlagen sowie der eigenen Identit&auml;tssuche der Menschen erlebbar machen.</p>");
